services:
  web: 
    container_name: ppond_on_rails
    build: . 
    image: ppond086/step3:latest 
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:migrate && bundle exec rails s -b '0.0.0.0'"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "84:3000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/rails